"""add_ocr_jobs_and_regions

Revision ID: bf7957ec3448
Revises: '001_initial_schema'
Create Date: 2026-08-24 23:44:48.840174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7957ec3448'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_processing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('engine_used', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('processing_time_ms', sa.Float(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('average_confidence', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_processing_jobs_created_at'), 'ocr_processing_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ocr_processing_jobs_inspection_id'), 'ocr_processing_jobs', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_ocr_processing_jobs_status'), 'ocr_processing_jobs', ['status'], unique=False)
    op.create_table('ocr_text_regions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_image_id', sa.String(length=36), nullable=True),
    sa.Column('recognized_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox_x', sa.Integer(), nullable=False),
    sa.Column('bbox_y', sa.Integer(), nullable=False),
    sa.Column('bbox_w', sa.Integer(), nullable=False),
    sa.Column('bbox_h', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('word_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_image_id'], ['evidence_images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['ocr_processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_text_regions_evidence_image_id'), 'ocr_text_regions', ['evidence_image_id'], unique=False)
    op.create_index(op.f('ix_ocr_text_regions_inspection_id'), 'ocr_text_regions', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_ocr_text_regions_job_id'), 'ocr_text_regions', ['job_id'], unique=False)
    with op.batch_alter_table('declaration_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_region_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_declaration_fields_ocr_region', 'ocr_text_regions', ['ocr_region_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('declaration_fields', schema=None) as batch_op:
        batch_op.drop_constraint('fk_declaration_fields_ocr_region', type_='foreignkey')
        batch_op.drop_column('ocr_region_id')
    op.drop_index(op.f('ix_ocr_text_regions_job_id'), table_name='ocr_text_regions')
    op.drop_index(op.f('ix_ocr_text_regions_inspection_id'), table_name='ocr_text_regions')
    op.drop_index(op.f('ix_ocr_text_regions_evidence_image_id'), table_name='ocr_text_regions')
    op.drop_table('ocr_text_regions')
    op.drop_index(op.f('ix_ocr_processing_jobs_status'), table_name='ocr_processing_jobs')
    op.drop_index(op.f('ix_ocr_processing_jobs_inspection_id'), table_name='ocr_processing_jobs')
    op.drop_index(op.f('ix_ocr_processing_jobs_created_at'), table_name='ocr_processing_jobs')
    op.drop_table('ocr_processing_jobs')
    # ### end Alembic commands ###
